version: '3.3'
services:
    eink-backend-image:
        container_name: eink-backend
        image: eink-backend-image
        volumes:
            - './example_data:/data'
        ports:
            - '9000:80'
        restart: unless-stopped
        environment:
            MOCK_FILE_NAME: data/srgssr_forecast_response.json
            DATABASE_FILE_NAME: data/empty_birthdays.db
            CALENDAR_FILE_NAME: data/entsorgungskalender_2022.ics
            DB_SECRET: eEiPnGE5C6k48tMBcG/BMCzgEreFkzl7MLD0UQhN5U4=
